kind: ConfigMap
apiVersion: v1
metadata:
  name: functions-config
data:
  MQ_URL: redis://redis-master.functions
  DB_URL: postgres://postgres:mysecretpassword@postgresql-master.functions/?sslmode=disable
